export const ACTION: Record<string, string> = {
  'user.create': 'ユーザー追加',
  'user.update': 'ユーザー編集',
  'user.delete': 'ユーザー削除',
  'user.import': 'ユーザーCSV取込',
  'department.create': '部門の追加',
  'department.update': '部門名の変更',
  'department.delete': '部門の削除',
  'slot.create': '枠の作成',
  'slot.update': '枠の編集',
  'slot.delete': '枠の削除',
  'post.create': '持ち場の追加',
  'post.update': '持ち場の編集',
  'post.delete': '持ち場の削除',
  'settings.availability_period': '希望の受付期間を変更',
  'availability.save': '希望を保存',
  'availability.admin_edit': '希望を管理者が編集',
  'assign.run': '自動割り当て',
  'assign.add': '割り当てを追加',
  'assign.remove': '割り当てを削除',
  'assign.lock': '割り当てを固定',
  'assign.unlock': '固定を解除',
  'assign.confirm': 'シフトを確定',
  'assign.unconfirm': '確定を解除',
};
